### ISSUE TITLE
inappropriate access to global variable

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-block_edwiser_site_monitor#11]
In [classes/utility.php#L44](https://github.com/WisdmLabs/moodle-block_edwiser_site_monitor/blob/cf85b9cc3014e3dbe8830322da09068361b7f83f/classes/utility.php#L44)

why are you using `$PAGE` here ? Seeing `edwiser_site_monitor_send_email()` usage I do not think you need to use it.

**Comment by wisdmyogeshshirsath** [comment]
Fixed [here](https://github.com/WisdmLabs/moodle-block_edwiser_site_monitor/commit/c07ea42912cdec3a7cde445a0cdc97504cbd752b)
