### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-block_edwiser_site_monitor#6]
![image](https://user-images.githubusercontent.com/2222386/55379974-0c497a80-551f-11e9-8042-7e5ca75a453b.png)

**Comment by wisdmyogeshshirsath** [comment]
Can you tell me your machine configuration?

**Comment by ak4t0sh** [comment]
Moodle 3.6.3 (Build: 20190311)
PHP 7.0
FYI : Due  to this error the installation process crashed and fails to create permissions and make the plugin unusable

**Comment by wisdmyogeshshirsath** [comment]
I wonder why this error appeared. PHP 7.0 supports const keyword. I'll change fix it.
